create database `order`;

USE `order`;

CREATE TABLE `USER`(
USER_ID     VARCHAR(20)  PRIMARY KEY,
NAME        NVARCHAR(25) NOT NULL,
PASSWORD    VARCHAR(30)  NOT NULL,
`E-MAIL`      VARCHAR(255) NOT NULL,
PERMISSION  INT          NOT NULL
);

CREATE TABLE `TYPE`(
TYPE_ID INT          PRIMARY KEY,
NAME    NVARCHAR(20) NOT NULL
);

CREATE TABLE `STATUS`(
STATUS_ID     INT      PRIMARY KEY,
`STATUS`      NCHAR(8) NOT NULL
);

CREATE TABLE PRODUCTS(
PRODUCT_ID    INT AUTO_INCREMENT PRIMARY KEY,
`TYPE`          INT          NOT NULL,
NAME          NVARCHAR(50) NOT NULL,
PRICE         INT          NOT NULL,
ORDER_DATE    DATE         NOT NULL,
DELIVERY_DATE DATE,
ORDER_STATUS  INT          NOT NULL,
ORDER_USER VARCHAR(20) NOT NULL,
FOREIGN KEY (ORDER_USER) REFERENCES `USER`(USER_ID),
FOREIGN KEY (`TYPE`) REFERENCES `TYPE`(TYPE_ID),
FOREIGN KEY (ORDER_STATUS) REFERENCES `STATUS`(STATUS_ID)
);


